DesafioDev/Controllers/CidadeController.cs
using DesafioDev.Models;
using DesafioDev.Models.Mapeamento;
using DesafioDev.Models.Service.Interface;
using DesafioDev.Repositorio.Models;
using DesafioDev.Repositorio.Services.Intefaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesafioDev.Controllers
{
    public class CidadeController : Controller
    {
        private ICidadeService _cidadeService;
        private IViewRenderService _viewRenderService;

        public CidadeController(ICidadeService cidadeService,
            IViewRenderService viewRenderService)
        {
            _cidadeService = cidadeService;
            _viewRenderService = viewRenderService;
        }

        public IActionResult Index()
        {
            CidadeViewModel viemodel = new CidadeViewModel();
            viemodel.listacidades = _cidadeService.BuscarCidades();

            return View(viemodel);
        }

        public IActionResult Form(int id)
        {
            CidadeViewModel cidadeViewModel = new CidadeViewModel();

            if (id > 0)
            {
                var cidade = _cidadeService.BuscarCidade(id);

                cidadeViewModel = CidadeMapeamento.MapearModelParaViewModel(cidade);
            }

            string Form = _viewRenderService.RenderToString(this, "Form", cidadeViewModel);

            return Json(new { view = Form });
        }

        [HttpPost]
        public IActionResult Salvar(CidadeViewModel cidade)
        {
            if (ModelState.IsValid)
            {
                bool retorno = _cidadeService.Salvar(CidadeMapeamento.MapearViewModelParaModel(cidade));

                if (retorno)
                {
                    CidadeViewModel viemodel = new CidadeViewModel();
                    viemodel.listacidades = _cidadeService.BuscarCidades();
                    string tabelaView = _viewRenderService.RenderToString(this, "_TabelaCidade", viemodel);

                    return Json(new { status = true, view = tabelaView, mensagem = "Cidade salva com sucesso!" });
                }
                else
                {
                    return Json(new { status = false, mensagem = "Não foi possível salvar!" });
                }
            }
            else
            {
                return Json(new { status = false, mensagem = "Campos obrigatórios não preenchidos!" });
            }
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            bool retorno = _cidadeService.Delete(id);

            if (retorno)
            {
                CidadeViewModel viemodel = new CidadeViewModel();
                viemodel.listacidades = _cidadeService.BuscarCidades();
                string tabelaView = _viewRenderService.RenderToString(this, "_TabelaCidade", viemodel);

                return Json(new { status = true, view = tabelaView, mensagem = "Cidade excluída com sucesso!" });
            }
            else
            {
                return Json(new { status = false, mensagem = "Não foi possível excluír cidade!" });
            }
        }
    }
}

DesafioDev/Controllers/PessoaController.cs
using DesafioDev.Models.Mapeamento;
using DesafioDev.Models.Service;
using DesafioDev.Models.Service.Interface;
using DesafioDev.Repositorio.Models;
using DesafioDev.Repositorio.Services.Intefaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DesafioDev.Controllers
{
    public class PessoaController : Controller
    {
        private IPessoaService _pessoaService;
        private ICidadeService _cidadeService;
        private IViewRenderService _viewRenderService;



        public PessoaController(IPessoaService pessoaService,
            ICidadeService cidadeService,
            IViewRenderService viewRenderService)
        {
            _pessoaService = pessoaService;
            _cidadeService = cidadeService;
            _viewRenderService = viewRenderService;
        }

        public IActionResult Index()
        {
            PessoaViewModel viemodel = new PessoaViewModel();
            viemodel.listapessoas = _pessoaService.FiltrarPessoas(null, 0, null);
            viemodel.selectcidades = CidadeMapeamento.MapearCidadesParaSelect(_cidadeService.BuscarCidades());

            return View(viemodel);
        }

        public IActionResult Form(int id)
        {
            PessoaViewModel pessoaViewModel = new PessoaViewModel();

            if (id > 0)
            {
                var pessoa = _pessoaService.BuscarPessoaId(id);

                pessoaViewModel = PessoaMapeamento.MapearModelParaViewModel(pessoa);
               

            }
            pessoaViewModel.selectcidades = CidadeMapeamento.MapearCidadesParaSelect(_cidadeService.BuscarCidades() ,false);

            string Form = _viewRenderService.RenderToString(this, "Form", pessoaViewModel);

            return Json(new { view = Form });


        }

        [HttpPost]
        public IActionResult Salvar(PessoaViewModel pessoa)
        {
            if (ModelState.IsValid)
            {
                bool retorno = _pessoaService.Salvar(PessoaMapeamento.MapearViewModelParaModel(pessoa));

                if (retorno)
                {
                    return Json(new { status = true, mensagem = "Pessoa salva com sucesso!" });
                }
                else
                {
                    return Json(new { status = false, mensagem = "Não foi possível salvar!" });
                }
            }
            else
            {
                return Json(new { status = false, mensagem = "Campos obrigatórios não preenchidos!" });
            }
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            bool retorno = _pessoaService.Delete(id);

            if (retorno)
            {
                return Json(new { status = true, mensagem = "Pessoa excluída com sucesso!" });
            }
            else
            {
                return Json(new { status = false, mensagem = "Não foi possível excluír pessoa!" });
            }
        }

        [HttpPost]
        public IActionResult Filtrar(PessoaViewModel filtro)
        {
            var pessoas = _pessoaService.FiltrarPessoas(filtro.tipo_pessoa, filtro.cidade_id, filtro.estado);
            var model = new PessoaViewModel
            {
                listapessoas = pessoas,

            };
            return PartialView("_TabelaPessoa", model);
        }


    }
}

DesafioDev/Views/Shared/_Estados.cshtml
<option value="AC">Acre</option>
<option value="AL">Alagoas</option>
<option value="AP">Amapá</option>
<option value="AM">Amazonas</option>
<option value="BA">Bahia</option>
<option value="CE">Ceará</option>
<option value="DF">Distrito Federal</option>
<option value="ES">Espírito Santo</option>
<option value="GO">Goiás</option>
<option value="MA">Maranhão</option>
<option value="MT">Mato Grosso</option>
<option value="MS">Mato Grosso do Sul</option>
<option value="MG">Minas Gerais</option>
<option value="PA">Pará</option>
<option value="PB">Paraíba</option>
<option value="PR">Paraná</option>
<option value="PE">Pernambuco</option>
<option value="PI">Piauí</option>
<option value="RJ">Rio de Janeiro</option>
<option value="RN">Rio Grande do Norte</option>
<option value="RS">Rio Grande do Sul</option>
<option value="RO">Rondônia</option>
<option value="RR">Roraima</option>
<option value="SC">Santa Catarina</option>
<option value="SP">São Paulo</option>
<option value="SE">Sergipe</option>
<option value="TO">Tocantins</option>

DesafioDev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesafioDev</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/datatable/datatables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <script src="~/js/datatable/datatables.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Sweetalert/sweetalert.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesafioDev</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cidade" asp-action="Index">Cidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Index">Pessoa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DesafioDev - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
</body>
</html>